-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 08:55:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GymPal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GymPal` ;

-- -----------------------------------------------------
-- Schema GymPal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GymPal` DEFAULT CHARACTER SET utf8 ;
USE `GymPal` ;

-- -----------------------------------------------------
-- Table `GymPal`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Admin` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Admin` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Coach` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Coach` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(64) NOT NULL,
  `joinedAt` DATE NULL,
  `experience` INT NULL,
  `isApproved` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`CoachClient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`CoachClient` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`CoachClient` (
  `id` INT NOT NULL,
  `coachId` INT NULL,
  `userId` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `coach_fk_idx` (`coachId` ASC) VISIBLE,
  INDEX `user_fk_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `coach_client_fk`
    FOREIGN KEY (`coachId`)
    REFERENCES `GymPal`.`Coach` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `user_coach_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`CoachRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`CoachRequest` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`CoachRequest` (
  `id` INT NOT NULL,
  `coachId` INT NULL,
  `userId` INT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_fk_idx` (`userId` ASC) VISIBLE,
  INDEX `coach_fk_idx` (`coachId` ASC) VISIBLE,
  CONSTRAINT `user_request_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `coach_requested_fk`
    FOREIGN KEY (`coachId`)
    REFERENCES `GymPal`.`Coach` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Exercise` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Exercise` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Goal` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Goal` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Meal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Meal` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Meal` (
  `id` INT NOT NULL,
  `mealName` VARCHAR(45) NULL,
  `totalCalories` BIGINT NULL,
  `Mealcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`MealEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`MealEntry` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`MealEntry` (
  `id` INT NOT NULL,
  `mealId` INT NULL,
  `userId` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_fk_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `meal_id`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`Meal` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Measurement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Measurement` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Measurement` (
  `id` INT NOT NULL,
  `weight` DOUBLE NULL,
  `height` DOUBLE NULL,
  `bfp` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`MeasurementEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`MeasurementEntry` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`MeasurementEntry` (
  `id` INT NOT NULL,
  `measurementId` INT NULL,
  `userId` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_fk_idx` (`userId` ASC) VISIBLE,
  INDEX `measurement_fk_idx` (`measurementId` ASC) VISIBLE,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `measurement_fk`
    FOREIGN KEY (`measurementId`)
    REFERENCES `GymPal`.`Measurement` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Profile` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Profile` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `age` INT NULL,
  `height` DOUBLE NULL,
  `gender` TINYINT NULL,
  `goalId` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `profile_goal_idx` (`goalId` ASC) VISIBLE,
  INDEX `profile_user_idx` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  CONSTRAINT `profile_goal`
    FOREIGN KEY (`goalId`)
    REFERENCES `GymPal`.`Goal` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `profile_user`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Set` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Set` (
  `id` INT NOT NULL,
  `weight` DOUBLE NULL,
  `reps` INT NULL,
  `workoutExerciseId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `workoutExercise_fk_idx` (`workoutExerciseId` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `workoutExercise_fk`
    FOREIGN KEY (`workoutExerciseId`)
    REFERENCES `GymPal`.`WorkoutExercise` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`User` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`User` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(64) NOT NULL,
  `joinedAt` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`Workout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`Workout` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`Workout` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `coachId` INT NULL,
  `name` VARCHAR(45) NULL,
  `notes` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_workout_idx` (`userId` ASC) VISIBLE,
  INDEX `coach_workout_idx` (`coachId` ASC) VISIBLE,
  CONSTRAINT `user_workout`
    FOREIGN KEY (`userId`)
    REFERENCES `GymPal`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coach_workout`
    FOREIGN KEY (`coachId`)
    REFERENCES `GymPal`.`Coach` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GymPal`.`WorkoutExercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`WorkoutExercise` ;

CREATE TABLE IF NOT EXISTS `GymPal`.`WorkoutExercise` (
  `id` INT NOT NULL,
  `workoutId` INT NULL,
  `exerciseId` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `workout_fk_idx` (`workoutId` ASC) VISIBLE,
  INDEX `exercise_fk_idx` (`exerciseId` ASC) VISIBLE,
  CONSTRAINT `workout_user_fk`
    FOREIGN KEY (`workoutId`)
    REFERENCES `GymPal`.`Workout` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exercise_workout_fk`
    FOREIGN KEY (`exerciseId`)
    REFERENCES `GymPal`.`Exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `GymPal` ;

-- -----------------------------------------------------
-- Placeholder table for view `GymPal`.`UserView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GymPal`.`UserView` (`id` INT, `email` INT, `joinedAt` INT);

-- -----------------------------------------------------
-- Placeholder table for view `GymPal`.`CoachView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GymPal`.`CoachView` (`id` INT, `firstName` INT, `lastName` INT, `email` INT, `joinedAt` INT, `experience` INT, `isApproved` INT);

-- -----------------------------------------------------
-- View `GymPal`.`UserView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`UserView`;
DROP VIEW IF EXISTS `GymPal`.`UserView` ;
USE `GymPal`;
CREATE  OR REPLACE VIEW `UserView` AS select id, email, joinedAt from User;

-- -----------------------------------------------------
-- View `GymPal`.`CoachView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GymPal`.`CoachView`;
DROP VIEW IF EXISTS `GymPal`.`CoachView` ;
USE `GymPal`;
CREATE  OR REPLACE VIEW `CoachView` AS select id, firstName, lastName, email, joinedAt, experience, isApproved from Coach;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
